name: EngageSphere tests 🧪

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and run backend
        run: |
          cd backend
          npm install
          npm start &
        env:
          CI: true

      - name: Install and run frontend
        run: |
          cd frontend
          npm install
          npm start &
        env:
          CI: true

      - name: Install and run tests
        run: |
          npm install
          npm test
        continue-on-error: true # Action should continue in failure situations

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
